version: 0.2

env:
  variables:
    NODE_ENV: "production"

phases:
  install:
    commands:
      - echo Installing Node v16...
      - curl -sL https://rpm.nodesource.com/setup_16.x | bash -
      - yum install -y nodejs
  pre_builds:
    commands:
      - echo Installing Dependencies...
      - npm install
  build:
    commands:
      - echo Building...
      - npm run build
artifacts:
  files:
    - "**/*"
  # discard-paths: no # no is default
  base-directory: dist
